//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IStackTrace.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public int PublishedBy { get; set; }
        public byte[] PublishedOn { get; set; }
        public string Title { get; set; }
    }
}
